### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by FBenzx** [soumickmj/StRegA#1]
I want to ask：In train.py file, where dose the 'ce_factor' parameter---'ce_factor'  come from?
![image](https://github.com/user-attachments/assets/f056bbee-568f-4a28-a52d-9af4a80a8640)

**Comment by FBenzx** [comment]
also the same to 'beta' below

**Comment by soumickmj** [comment]
This is only a dummy train function, the whole script is not provided. I will upload the whole script soon.

both ce_factor and beta are constants that can be defined at the start of the file or supplied as paramters.
The values we used are as follows:
ce_factor=0.5
beta=0.01

**Comment by FBenzx** [comment]
thanks a lot ^ ^
